### ISSUE TITLE
Is it broken right now?

### ISSUE THREAD

**Issue by D3SOX** [jeroentvb/spicetify-playlist-icons#1]
The extension no longer works for me, how to debug this?
Spotify version: 1.1.84.716
Spicetify version: 2.9.8

**Comment by jeroentvb** [comment]
Spotify updated some classnames which spicetify used to add the `spicetify-playlist-list` class, which resulted in spicetify not setting the class.
That `spicetify-playlist-list` is used by this extension to get the playlist container, which 'broke' the extension. I've created a PR to fix this (https://github.com/spicetify/spicetify-cli/pull/1654). Might take some time for it to be merged & released.

Thanks for brining this to my attention. I didn't know, because I mostly use macOs, on which it didn't break.

**Comment by D3SOX** [comment]
@jeroentvb Thanks! I'm going to close this since it's not an issue with this extension.
