### ISSUE TITLE
Doesn't work since latest update

### ISSUE THREAD

**Issue by OnlYKai** [jeroentvb/spicetify-playlist-icons#17]
maybe it's because i'm using the old ui, but it worked before the update
![image](https://github.com/jeroentvb/spicetify-playlist-icons/assets/67548894/48198cf8-7c05-4f80-b199-36eee6d67f2b)

**Comment by jeroentvb** [comment]
Click your account image in the top left, hover over playlist icons and select legacy mode.

I disabled rendering the playlist icons by default, because Spotify renders them in the new UI. This prevents the code running while it's not necessary. It does still render playlist icons in the 'add to playlist' context menu for all users.

**Comment by OnlYKai** [comment]
ty that fixes it
i still have a problem tho, when i tried fixing it i installed the extension manually and it's still in the list of "spicetify config extensions" how do i remove it?

**Comment by OnlYKai** [comment]
found it in spicetify docs everything works now

**Comment by kiprasmel** [comment]
hey sorry this is completely unrelated but @OnlYKai  what theme/background is that? o.O

**Comment by OnlYKai** [comment]
@kiprasmel i think it's called retroblur (for some reason there are 2 versions, one works the other one doesn't)

**Comment by kiprasmel** [comment]
damn that's awesome, thanks. too bad it flickers so much on macos.. will see if can fix.

yeah i think the other one is the older version

edit: i ended up w/ the original theme which retrolbur is based on -- galaxy:
https://github.com/harbassan/spicetify-galaxy
and added the sweet background image from retroblur -- works great! thanks
