### ISSUE TITLE
it won't let me uninstall it

### ISSUE THREAD

**Issue by 1stFlower** [jeroentvb/spicetify-playlist-icons#6]
I downloaded playlist icons from the marketplace and when I try to uninstall it, click "reload now" and it is still there. Worst of all, there is two of them (no pun intended) now, I can uninstall the 2nd one, but after another reload it still will be there. So how to uninstall it?

**Comment by jeroentvb** [comment]
This is a marketplace issue, not one caused by playlist icons.

If you open the spotify dev console, and navigate to the application tab -> localstorage, there should be a key related to the marketplace holding the info of all installed extensions. There you can remove playlist icons.

If it doesn't work, or the key is not there, I would recommend to reset the marketplace.
